// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxtcthasolwpqscgkfbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dGN0aGFzb2x3cHFzY2drZmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTM1NTQsImV4cCI6MjA2MzIyOTU1NH0.hi2OEw65pc6nr8BjMBj58QtvDK5MdIfumTW5OVzWT-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);